### ISSUE TITLE
Include blog in website?

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/apereo.foundation#1]
Should the Apereo blog be included in the website, or kept as a separate site?

**Comment by ChristianMurphy** [comment]
For me the question comes down to the distinction between official content and content that are personal statements.
From the current apereo blog:

> Unless otherwise noted, all authors post here wearing their individual Apereo participant hats. Opinions, statements, and comments expressed via this blog do not necessarily reflect those of the Apereo Foundation.

If content is mixed how would official vs individual content be distinguished?

**Comment by apetro** [comment]
I agree it's easiest to keep these separate, and continues to help address historical angst about clarifying that the apereo.github.io blog are not official statements ( https://github.com/apereo/apereo.github.io/issues/39 ).
