### ISSUE TITLE
Project metadata

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/apereo.foundation#16]
Apereo.org has some nifty links to repositories, blogs, downloads, etc.
This project should keep track of some standard fields that can be shown both on the project page and can enhance other views through collection metadata.
E.G. https://www.apereo.org/projects/apereo-oae
https://jekyllrb.com/docs/frontmatter/
https://jekyllrb.com/docs/collections/

**Comment by btopro** [comment]
create a schema for expressing projects (with a fallback to metadata blob) and then you could easily have people fill it out on their own and update the yaml / json independen t of any system in order to load it

**Comment by ChristianMurphy** [comment]
Good point,
jekyll supports that as well through https://jekyllrb.com/docs/datafiles/

**Comment by btopro** [comment]
oh nice, I'd recommend leveraging the `_data/data.json` or whatever name; that way it would be easy to structure components to load that data in and leverage either in jekyll templates or loaded into web components via `iron-ajax` calls
