### ISSUE TITLE
Add project README

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/apereo.foundation#4]
Give a high level overview of what this site is

**Comment by apetro** [comment]
Relatedly, I think I'd like a refactor to move the website content into a `/docs` directory and reserve the rest of the root directory for meta. That is, we need both documentation about this project, about how to locally build from source, about contributing to, about website architecture and design and maybe editorial voice and style guide and... well, whatever meta stuff we need. And then we also need actual website content. Some of that stuff could be in the actual website content, and maybe should be, but some of it would best not be.

So namespace the actual website content into `/docs` and thereby create namespace for not-actually-website-content stuff too. 

It maybe goes without saying that I'll offer a pull request along these lines when I can get to it.

**Comment by ChristianMurphy** [comment]
My original thought was to use the top level directory for project related content, and use `.github` for documentation about the site.
I'd be willing to go the `/docs` route though.
