### ISSUE TITLE
local issue: no styling on /

### ISSUE THREAD

**Issue by apetro** [ChristianMurphy/apereo.foundation#44]
So I get no styling on / when rendering locally via the Docker image. Everything else seems to work fine. Seems to be only local since https://apereo.foundation/ styles just fine.

Have not yet sufficiently troubleshot (presumably once I sufficiently troubleshoot I'll resolve some local issue I haven't discovered yet.)

**Comment by ChristianMurphy** [comment]
Are there any browser console logs or error codes in the browser network console?

**Comment by apetro** [comment]
No console log except that requested localhost:4000 . No error codes in network console, indeed no attempts to source anything other than localhost:4000. 

However, in a fresh Docker container, works fine. So I'm figuring it was just a glitch in the matrix.
